site_name: Keras Documentation
# theme: readthedocs
docs_dir: sources
repo_url: http://github.com/fchollet/keras
site_url: http://keras.io/
theme_dir: ../keras/docs/theme
site_description: 'Documentation for Keras, the Python Deep Learning library.'

dev_addr: '0.0.0.0:8000'
google_analytics: ['UA-61785484-1', 'keras.io']


pages:
- Home: index.md
- 初めに:
  - Sequentialモデルのガイド: getting-started/sequential-model-guide.md
  - Functional APIのガイド: getting-started/functional-api-guide.md
  - FAQ: getting-started/faq.md
- モデル:
  - モデルについて: models/about-keras-models.md
  - Sequentialモデル: models/sequential.md
  - Modelクラス (functional API): models/model.md
- レイヤー:
  - レイヤーについて: layers/about-keras-layers.md
  - Coreレイヤー: layers/core.md
  - Convolutionalレイヤー: layers/convolutional.md
  - Recurrentレイヤー: layers/recurrent.md
  - Embeddingレイヤー: layers/embeddings.md
  - Advanced Activationsレイヤー: layers/advanced-activations.md
  - Normalizationレイヤー: layers/normalization.md
  - Noiseレイヤー: layers/noise.md
  - レイヤーラッパー: layers/wrappers.md
  - オリジナルのKerasレイヤーを作成する: layers/writing-your-own-keras-layers.md
- データの前処理:
  - シーケンスの前処理: preprocessing/sequence.md
  - テキストの前処理: preprocessing/text.md
  - 画像の前処理: preprocessing/image.md
- Objectives: objectives.md
- Optimizers: optimizers.md
- Activations: activations.md
- Callbacks: callbacks.md
- Datasets: datasets.md
- Backend: backend.md
- Initializations: initializations.md
- Regularizers: regularizers.md
- Constraints: constraints.md
- Visualization: visualization.md
- Scikit-learn API: scikit-learn-api.md




